services:
  web:
    build: .
    environment:
      RUN_MODE: web
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["python", "manage.py", "runweb"]
    restart: unless-stopped

  bot:
    build: .
    environment:
      RUN_MODE: bot
    env_file:
      - .env
    depends_on:
      - web
    command: ["python", "manage.py", "runbot"]
    restart: unless-stopped
